exports_files(
    ["rules.bzl"],
    visibility = ["//docs:__pkg__"],
)

# Only used to generate the docs in //docs.
filegroup(
    name = "bzl_srcs",
    srcs = glob(["*.bzl"]),
    visibility = ["//docs:__pkg__"],
)
