exports_files(
    [
        "config.nu",
        "env.nu",
    ],
    visibility = ["//visibility:public"],
)

exports_files(
    [
        "nu_binary.bzl",
        "nu_genrule.bzl",
        "nu_library.bzl",
        "providers.bzl",
    ],
    visibility = ["//docs:__pkg__"],
)
