load("//nu/private:providers.bzl", "NuInfo")
load("//nu/toolchains:defs.bzl", "NUSHELL_TOOLCHAIN_TYPE")

def _nu_genrule_impl(ctx):
    nu = ctx.toolchains[NUSHELL_TOOLCHAIN_TYPE].nu
    variables = {
        "inputs": [f.path for f in ctx.files.inputs],
        "outputs": [f.path for f in ctx.outputs.outputs],
    }
    config_files = [ctx.file._env_config, ctx.file._config]
    variables_file = ctx.actions.declare_file("%s_env.json" % ctx.label.name)
    ctx.actions.write(
        output = variables_file,
        content = json.encode(variables),
    )
    cmd = "open %s | let bazel; %s" % (variables_file.path, ctx.attr.cmd)

    module_inputs = [t[NuInfo].scripts for t in ctx.attr.modules]
    data_inputs = [dep[DefaultInfo].files for dep in ctx.attr.data]
    all_inputs = depset(
        ctx.files.inputs + [variables_file] + config_files,
        transitive = module_inputs + data_inputs,
    )
    args = ctx.actions.args()
    args.add("--env-config", ctx.file._env_config)
    args.add("--config", ctx.file._config)
    args.add("-c", cmd)

    ctx.actions.run(
        executable = nu,
        inputs = all_inputs,
        outputs = ctx.outputs.outputs,
        arguments = [args],
    )

nu_genrule = rule(
    implementation = _nu_genrule_impl,
    attrs = {
        "cmd": attr.string(
            mandatory = True,
            doc = "The nu shell command to run",
        ),
        "inputs": attr.label_list(
            doc = "The input files accessible to the nu shell command",
            allow_files = True,
        ),
        "outputs": attr.output_list(
            doc = "The output files generated by the nu shell command",
            mandatory = True,
            allow_empty = False,
        ),
        "modules": attr.label_list(
            doc = "Nushell modules to use in this script",
            allow_empty = True,
            providers = [NuInfo],
        ),
        "data": attr.label_list(
            doc = "Additional files which are available to the nu shell command",
            allow_files = True,
        ),
        "tools": attr.label_list(
            doc = """
            Executable targets which are available to the nu shell command.
            Runfiles are also automatically made available.
            """,
            cfg = "exec",
        ),
        "_env_config": attr.label(
            doc = "Nushell env.nu file",
            allow_single_file = [".nu"],
            mandatory = False,
            default = "//nu/private:env.nu",
        ),
        "_config": attr.label(
            doc = "Nushell config.nu file",
            allow_single_file = [".nu"],
            mandatory = False,
            default = "//nu/private:config.nu",
        ),
    },
    toolchains = [NUSHELL_TOOLCHAIN_TYPE],
)
