load("@hermetic_launcher//launcher:lib.bzl", "launcher")
load("//nu/private:nu_binary.bzl", "nu_binary")
load("//nu/private:nu_library.bzl", "nu_library")

# A minimal stand-in for `@bazel_skylib//rules:write_file.bzl`'s `write_file`.
_write_nu_script = rule(
    implementation = lambda ctx: ctx.actions.write(
        output = ctx.outputs.out,
        content = ctx.attr.content,
    ),
    attrs = {
        "content": attr.string(mandatory = True),
        "out": attr.output(mandatory = True),
    },
)

def _nu_genrule_run_impl(ctx):
    input_args = ctx.actions.args()
    input_args.add_all([launcher.to_rlocation_path(f) for f in ctx.files.inputs])
    input_args.use_param_file("%s", use_always = True)

    output_args = ctx.actions.args()
    output_args.add_all(ctx.outputs.outputs)
    output_args.use_param_file("%s", use_always = True)

    tool_args = ctx.actions.args()
    tool_args.add_all([
        launcher.to_rlocation_path(tool[DefaultInfo].files_to_run.executable)
        for tool in ctx.attr.tools
    ])
    tool_args.use_param_file("%s", use_always = True)

    ctx.actions.run(
        executable = ctx.executable.binary,
        arguments = [input_args, output_args, tool_args],
        inputs = depset(ctx.files.inputs),
        tools = [tool[DefaultInfo].files_to_run for tool in ctx.attr.tools],
        outputs = ctx.outputs.outputs,
        mnemonic = "NuGenrule",
        progress_message = "Running nu_genrule %{label}",
    )

_nu_genrule_run = rule(
    implementation = _nu_genrule_run_impl,
    doc = "Runs the pre-compiled nu_binary executable",
    attrs = {
        "binary": attr.label(executable = True, cfg = "exec", mandatory = True),
        "inputs": attr.label_list(allow_files = True),
        "tools": attr.label_list(cfg = "exec"),
        "outputs": attr.output_list(mandatory = True, allow_empty = False),
    },
)

def _nu_genrule_script(cmd):
    return """def main [inputs_file: string, outputs_file: string, tools_file: string] {{
    let outputs = (open $outputs_file | lines)
    let input_keys = (open $inputs_file | lines)
    let tool_keys = (open $tools_file | lines)
    let rf = (runfiles create)
    let bazel = {{
        outputs: $outputs
        inputs: ($input_keys | each {{|key| runfiles rlocation $rf $key }})
        tools: ($tool_keys | each {{|key| runfiles rlocation $rf $key }})
    }}
{cmd}
}}
""".format(cmd = cmd)

def _nu_genrule_impl(name, visibility, cmd, outputs, inputs, tools, deps, data, **kwargs):
    script_name = "{}_main".format(name)
    binary_name = "{}_bin".format(name)
    data_deps_library = "{}_data_deps".format(name)

    _write_nu_script(
        name = script_name,
        out = "{}.nu".format(name),
        content = _nu_genrule_script(cmd),
    )

    # We require this intermediate `nu_library` to allow `data` and `deps` to be
    # configurable. The trivial solution is to use `data = inputs + data` in
    # `nu_binary`, but this analysis-time evaluation is not allowed on
    # configurable attributes.
    nu_library(
        name = data_deps_library,
        data = data,
        deps = deps,
    )

    nu_binary(
        name = binary_name,
        main = script_name,
        deps = [data_deps_library],
        data = inputs,
        tools = tools,
        cfg = "exec",
    )

    _nu_genrule_run(
        name = name,
        visibility = visibility,
        binary = binary_name,
        inputs = inputs,
        tools = tools,
        outputs = outputs,
        **kwargs
    )

nu_genrule = macro(
    doc = "Generates `outputs` by running a nushell command.",
    implementation = _nu_genrule_impl,
    inherit_attrs = "common",
    attrs = {
        "cmd": attr.string(
            doc = "The nushell command to run.",
            mandatory = True,
            configurable = False,
        ),
        "outputs": attr.output_list(
            doc = "The output files generated by `cmd`.",
            mandatory = True,
            allow_empty = False,
        ),
        "inputs": attr.label_list(
            doc = "Input files accessible via `$bazel.inputs` (and runfiles).",
        ),
        "tools": attr.label_list(
            doc = "Executable targets (built for the exec platform) that `cmd` can call; their resolved paths are in `$bazel.tools`, in order.",
        ),
        "deps": attr.label_list(
            doc = "Nushell modules dependencies available to `cmd` via `use`.",
        ),
        "data": attr.label_list(
            doc = "Additional files available to `cmd` via `runfiles`.",
        ),
    },
)
